# Generated by Django 4.2 on 2025-11-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('salon_num', models.IntegerField()),
                ('duracion_semanas', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('cupo_maximo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('experiencia_anios', models.PositiveIntegerField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cantidad_stock', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='app_TallerdeArte.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='app_TallerdeArte.instructor'),
        ),
    ]
