# Generated by Django 5.2.6 on 2025-11-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_TallerdeArte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='app_TallerdeArte.curso'),
        ),
    ]
